name: Build JipperResourcePack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore JipperResourcePack.sln

    - name: Build Solution
      run: msbuild JipperResourcePack.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JipperResourcePack-DLL
        path: |
          **/bin/Release/*.dll
